@baseUrl = http://localhost:3000

###  Busca todos os recados

# @name  ControllerMsgAll
GET {{baseUrl}}/recados/



###  busca somente um recado 

# @name  ControllerMsgOne
GET {{baseUrl}}/recados/1


### Cria um novo Recado

# @name  ControllerMsgCreate
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "leonardo",
    "de": "leonardo",
    "para": "jacqueline"
}

###  Atualiza um recado
# @name  ControllerMsgUpdate
PATCH   {{baseUrl}}/recados/2
Content-Type: application/json

  {
    "texto": "Atualizado 3",
    "lido": true
  
  }

### Deleta um Recado 
# @name  ControllerMsgDelete
DELETE   {{baseUrl}}/recados/1

